#цель: зависимость
#[tab] команда


BIN = TCPClient
SOURCES = main.c
HEADERS = main.h
CC := gcc

all:
	$(CC) $(SOURCES) -lc -o $(BIN).out
$(BIN): $(HEADERS)

run: all
	./$(BIN).out

run2:
	./$(BIN).out

#clean:
#	rm -rf $(BIN) *.o $(BIN).out



















